### PR TITLE
Update gotutorial.md

### PR DESCRIPTION
**Pull request by bonavadeur**
wrong constant name, I changed Person_PHONE_TYPE_HOME to PhoneType_PHONE_TYPE_HOME

### CODE REVIEW

**Comment by Logofile** [comment]
Thanks for your contributiont to improving/fixing the docs!

This PR is missing a CLA. Once you've agreed to the CLA, I'll be able to assess the contribution.

**Comment by Logofile** [comment]
This PR is missing a CLA. Once you've agreed to the CLA, I'll be able to assess the contribution.

**Comment by bonavadeur** [comment]
Hi David,
I agreed to the CLA.
Hiep.

Vào Th 2, 15 thg 4, 2024 vào lúc 20:45 David Castro <
***@***.***> đã viết:

**Comment by Logofile** [comment]
This issue is still indicating that the **cla/google** check is failing. I cannot merge the PR without the CLA test passing.

**Comment by Logofile** [comment]
That worked; thanks! I'll see if I can get this done this week.

**Comment by Logofile** [comment]
This fix was incorporated in [this PR that bundled various updates](https://github.com/protocolbuffers/protocolbuffers.github.io/pull/161). Thanks for sending the update!

**Pull request closed without merging**
